import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Hero from "./components/Hero";
import Footer from "./components/Footer";
import { Montserrat } from "next/font/google";
import Nav from "./components/Nav";
import Nav2 from "./components/Nav2";


const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['100', '400', '200', '300', '500'],
  style: ['normal', 'italic'],
  variable: '--font-'
 })


export const metadata: Metadata = {
  title: "Jenn Evolve Sound Healing and Lifecoaching",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth" lang="en">
      <div className='overflow-hidden'>
        <body className={montserrat.className}>
        <Hero />
          <main className="overflow-hidden">
            {children}
          </main>
        <Footer />
      </body>
      </div>
    </html>
  );
}
